display-name: "Автопереплавка"
description: "&rПереплавляет скопанные руды"
type: special

targets:
  - pickaxe
conflicts: [ ]
rarity: special
max-level: 1

tradeable: true
discoverable: true
enchantable: true

effects:
  - id: autosmelt
    args:
      drop_xp: true
    triggers:
      - block_item_drop
triggers:
  - mine_block

conditions: [ ]
